### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by xiaopangju** [Ravenclaw-OIer/enmoegirl-backup#1]
我记得这个仓库的owner是中国人，所以我就直接用中文发了。
第一个问题：我现在需要到这里备份英文wiki吗？
第二个问题：如果需要，那么我是不是直接复制粘贴源代码内容就可以了？

**Comment by ShizuhaAki** [comment]
As the debate on closing the English version ceased currently, it is not that urgent to perform the back up right now.

If you are interested, however, then you can just paste source code here!

Remember to create a folder for the pages/put them into the correct folder! The folder name should be the namespace name, e.g ```Template``` for template pages and ```main``` for the main namespace (article namespace) See README.md for more information.

**Comment by xiaopangju** [comment]
thanks! is the source code means wikitext(e.g <ref>xxxxxxx</ref>)and all of the page's content?

已从 Outlook Mobile<https://aka.ms/blhgte> 发送
