### ISSUE TITLE
You should edit the URL now

### ISSUE THREAD

**Issue by xiaopangju** [Ravenclaw-OIer/enmoegirl-backup#7]
the English vision domain is https://en.moegirl.org.cn/ now,not https://en.moegirl.org

**Comment by xiaopangju** [comment]
![image](https://user-images.githubusercontent.com/56964531/97764142-98cb7d00-1b48-11eb-91b3-07db4b57e1e9.png)
I said here, on the right.

**Comment by ShizuhaAki** [comment]
Fixed
